### ISSUE TITLE
Check pirogue-eve-collector's suricata restart on low memory systems

### ISSUE THREAD

**Issue by CyrilBrulebois** [PiRogueToolSuite/pirogue-admin#19]
While adjusting some other things, I've just stumbled upon a FIXME in `pirogue-eve-collector`:

```yaml
files:
  - src: suricata.yaml
    dst: /etc/suricata/suricata.yaml
    variables:
      - name: ISOLATED_NETWORK
        type: cidr_network
      - name: ISOLATED_INTERFACE
    actions:
      # FIXME: Check what happens when it's conditionally-skipped.
      #        Also, try-restart exists.
      - systemctl restart suricata
```

Since @TontonSancho has a low-memory Pi 4, it would be nice to have some feedback regarding that particular package: is the `restart` OK there? The first one would happen when the initial configuration is deployed, at the very end of the `pirogue-base` installation.

This is not critical/urgent at this point, just something I thought we should double-check. Worst case I can simulate hitting the condition (by adding a few zeroes).
